packages:
  - 'apps/*'
  - 'packages/*'
  - 'packages/tooling/*'

catalog:
  next: "^16.0.10"
  react: "^19.2.3"
  react-dom: "^19.2.3"
  tailwindcss: "^4.1.18"
  zod: "^4.2.1"
  drizzle-orm: "^0.45.1"
  hono: "^4.11.1"
  lucide-react: "^0.561.0"
  typescript: "^5.9.3"
  vite: "^8.0.0-beta.5"
  tsdown: "^0.18.2"
  tsx: "^4.21.0"
  mysql2: "^3.16.0"
  drizzle-kit: "^0.31.8"
  drizzle-seed: "^0.3.1"
  drizzle-zod: "^0.8.3"
  "@trpc/server": "^11.8.1"
  "@types/node": "^25.0.3"
  "@types/react": "^19.2.7"
  "@types/react-dom": "^19.2.3"
  "@vitejs/plugin-legacy": "^7.2.1"
  "@vitejs/plugin-react": "^5.1.2"
  "@tailwindcss/vite": "^4.1.18"
