packages:
  - 'apps/*'
  - 'packages/*'
  - 'packages/tooling/*'

catalog:
  next: "^16.0.10"
  react: "^19.2.3"
  react-dom: "^19.2.3"
  tailwindcss: "^4.1.18"
  zod: "^4.2.1"
  drizzle-orm: "^0.45.1"
  hono: "^4.11.1"
  lucide-react: "^0.561.0"
  typescript: "^5.9.3"
  tsdown: "^0.18.2"
  tsx: "^4.21.0"
  "@types/node": "^25.0.3"
  "@types/react": "^19.2.7"
  "@types/react-dom": "^19.2.3"