// ⚡️ AUTO-GENERATED BY RUST TOOL - DO NOT EDIT
import type { z } from 'zod'
import * as postTable from './post'
import * as projectTable from './project'
import * as userTable from './user'

export const schema = {
  ...projectTable,
  ...userTable,
  ...postTable,
}

export type { Project } from './project'
// --- Entity: Project ---
export { insertProjectSchema, projects, selectProjectSchema } from './project'
export type NewProject = z.infer<typeof projectTable.insertProjectSchema>

export type { User } from './user'
// --- Entity: User ---
export { insertUserSchema, selectUserSchema, users } from './user'
export type NewUser = z.infer<typeof userTable.insertUserSchema>

export type { Post } from './post'
// --- Entity: Post ---
export { insertPostSchema, posts, selectPostSchema } from './post'
export type NewPost = z.infer<typeof postTable.insertPostSchema>
