// ⚡️ AUTO-GENERATED BY RUST TOOL - DO NOT EDIT

import { postRouter } from './router/post'
import { projectRouter } from './router/project'
import { userRouter } from './router/user'
import { createTRPCRouter } from './trpc'

export const appRouter = createTRPCRouter({
  project: projectRouter,
  user: userRouter,
  post: postRouter,
})

export type AppRouter = typeof appRouter
